### ISSUE TITLE
AHU Equips and Points are not populated on model import

### ISSUE THREAD

**Issue by TShapinsky** [NatLabRockies/hasty#69]
When importing a haystack file equips and points are not populated for AHUs. When creating model from scratch in hasty these fields are populated.

# Create Custom Site
![image](https://user-images.githubusercontent.com/8397034/148112263-a44e8ada-e351-48bd-ba62-f1166b6a4062.png)
![image](https://user-images.githubusercontent.com/8397034/148111989-3b241b08-2087-4899-a8ac-7dd98a958037.png)

# Create Site from File
![image](https://user-images.githubusercontent.com/8397034/148112171-30b3f448-ee11-444d-9c2e-7e9003041fb1.png)
![image](https://user-images.githubusercontent.com/8397034/148112063-63577ebe-2747-468f-9e32-40d2830bfc09.png)

**Comment by MatthewSteen** [comment]
I think #5 can be closed with this one.
